name: Average Cases

on:
  push:
    branches:
      - master

jobs:
  average:
    name: Average
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Average
        uses: xHyroM/covid19-stats/.github/actions/average@master
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
