name: Covid19-Cases

on: [workflow_dispatch]

jobs:
  cases:
    name: Cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stats
        uses: xHyroM/covid19-stats/.github/actions/cases@master
        with:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}